/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OhbAnunciocmp {
        "Assinatura": string;
        "Comentario": string;
        "Horario": string;
        "Titulo": string;
    }
}
declare global {
    interface HTMLOhbAnunciocmpElement extends Components.OhbAnunciocmp, HTMLStencilElement {
    }
    var HTMLOhbAnunciocmpElement: {
        prototype: HTMLOhbAnunciocmpElement;
        new (): HTMLOhbAnunciocmpElement;
    };
    interface HTMLElementTagNameMap {
        "ohb-anunciocmp": HTMLOhbAnunciocmpElement;
    }
}
declare namespace LocalJSX {
    interface OhbAnunciocmp {
        "Assinatura"?: string;
        "Comentario"?: string;
        "Horario"?: string;
        "Titulo"?: string;
    }
    interface IntrinsicElements {
        "ohb-anunciocmp": OhbAnunciocmp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ohb-anunciocmp": LocalJSX.OhbAnunciocmp & JSXBase.HTMLAttributes<HTMLOhbAnunciocmpElement>;
        }
    }
}
